/* Editorial content is local: no runtime API, account or build dependency. */
window.HUB = {
  stages: [
    {id:'capture',title:'Capture',subtitle:'Geometry meets appearance',description:'LiDAR measures distances with laser pulses. Cameras capture colour and texture. Together they can make a scene easier to inspect.',output:'Colourised point clouds',repos:['Sensor_Computer'],paper:'colour'},
    {id:'calibrate',title:'Calibrate',subtitle:'Make observations agree',description:'Spatial calibration, optical correction and timing estimation address different sources of measurement disagreement.',output:'Transforms, correction tables and timing offsets',repos:['single-shot-lidar-camera-calibration','enclosure-aware-lidar-correction','livox-avia-camera-timing','rotating-target-calibration-studio'],paper:'measurement'},
    {id:'protect',title:'Integrate',subtitle:'Engineering inside an enclosure',description:'Sensors and embedded processing must work within thermal, power, optical and communication constraints.',output:'Protected sensing and pre-deployment evidence',repos:['Sensor_Computer','3D_monitoring_device_simulation_underground'],paper:'hardware'},
    {id:'reconstruct',title:'Reconstruct',subtitle:'Many views, one scene',description:'Coverage tools guide viewing geometry. Physical spacing and alignment constraints help resolve repetitive underground structures.',output:'Common-frame scenes and device transforms',repos:['Lidar_camera_FOV_analysis','Multi_device_reconstruction-pose_graph','Dynamic_Object_Detection','Meshing_toolkit','Central_Monitoring_Platform'],paper:'array'},
    {id:'interpret',title:'Interpret',subtitle:'From objects to relationships',description:'Semantic perception identifies scene elements; graphs, rules and contextual reasoning organise spatial hazard evidence.',output:'Detections, scene graphs and reasoning evidence',repos:['Scene-Graph_Mine-Safety'],paper:'safety'},
    {id:'extend',title:'Extend',subtitle:'New questions from 3D observations',description:'A creep-monitoring concept/prototype explores gradual relative movement of roof supports.',output:'Relative trajectories and displacement',repos:['Creep_Monitoring'],paper:'synthesis'}
  ],
  papers: [
    {id:'review',chapter:'2',label:'Monitoring requirements',title:'From Point Sensors to Spatial Hazard Interpretation in Underground Coal Mining: A Critical Review of Longwall Monitoring, Validation and Deployment Readiness',authors:'P. Ranasinghe, S. Raval, B. Banerjee and I. Canbulat',venue:'Review manuscript · SSRN 7171901',status:'Under review',url:'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=7171901',evidence:'Literature review and documented search scope',contribution:'Connects sensing capabilities with validation and deployment-readiness criteria.'},
    {id:'spatial',chapter:'3.1',label:'Spatial calibration',title:'An Automated Single-Shot LiDAR and Camera Extrinsic Calibration Method Using Image Processing',authors:'P. Ranasinghe, D. Patra, B. Banerjee and S. Raval',venue:'IGARSS 2025 · DOI 10.1109/IGARSS55030.2025.11242429',status:'Published conference paper',url:'https://doi.org/10.1109/IGARSS55030.2025.11242429',evidence:'Controlled calibration experiment',contribution:'Automates checkerboard correspondence and extrinsic estimation from one paired capture.'},
    {id:'measurement',chapter:'3.2',label:'Enclosure and timing',title:'Correcting time offsets and enclosure-induced measurement distortions in LiDAR–camera systems',authors:'P. Ranasinghe, D. Patra, A. Mawathage, B. Banerjee, C. Ye, B. Nan and S. Raval',venue:'Measurement 285 (2026), 122285 · DOI 10.1016/j.measurement.2026.122285',status:'Published journal article',url:'https://doi.org/10.1016/j.measurement.2026.122285',evidence:'Analytical modelling, simulation and laboratory experiments',contribution:'Treats time alignment, LiDAR refraction and enclosure-aware camera/extrinsic calibration as a combined measurement chain.'},
    {id:'timing',chapter:'3.3',label:'Transferable temporal estimation',title:'A Rotating Aperture Target with a Common Geometric Estimator for Temporal Calibration of Heterogeneous Sensors',authors:'P. Ranasinghe, D. Patra, B. P. Banerjee and S. Raval',venue:'SSRN 7513129 · DOI 10.2139/ssrn.7513129 · posted 23 September 2026',status:'Under review',url:'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=7513129',evidence:'22 configurations: three hardware tests; remaining configurations simulated',contribution:'Recovers a common angular state across heterogeneous acquisition architectures.'},
    {id:'colour',chapter:'3.4',label:'Useful colour in low light',title:'LiDAR Point Cloud Colourisation Using Multi-Camera Fusion and Low-Light Image Enhancement',authors:'P. Ranasinghe, D. Patra, B. Banerjee and S. Raval',venue:'Sensors 25 (2025), 6582 · DOI 10.3390/s25216582',status:'Published journal article · CC BY',url:'https://doi.org/10.3390/s25216582',evidence:'Velodyne Puck Hi-Res with four cameras; platform-specific low-light tests',contribution:'Combines multi-camera colourisation, colour consistency and low-light enhancement.'},
    {id:'hardware',chapter:'4',label:'Protected sensing unit',title:'Design and Pre-Deployment Validation of a Flameproof LiDAR–Camera Unit for Colourised 3D Monitoring of Underground Longwall Operations',authors:'P. Ranasinghe, B. Banerjee and S. Raval',venue:'Local manuscript · arXiv 2605.02516v1 is an earlier title/version',status:'Under review',url:'https://arxiv.org/abs/2605.02516',evidence:'Bench tests, thermal modelling and representative longwall simulation',contribution:'Integrates a solid-state LiDAR, RGB camera and embedded processor within a certified flameproof enclosure.',versionNote:'The linked May 2026 manuscript is titled “Development and Validation of an Integrated LiDAR-Camera System for Real-Time Monitoring of Underground Longwall Operations”. It is not the exact revised local manuscript.'},
    {id:'array',chapter:'5',label:'Face-wide reconstruction',title:'A Scalable Array of Integrated LiDAR–Camera Units for Continuous Colourised 3D Monitoring of Underground Longwall Operations',authors:'P. Ranasinghe, D. Patra, B. Banerjee, C. Ye, B. Nan and S. Raval',venue:'Local manuscript · SSRN 7209040',status:'Under review',url:'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=7209040',evidence:'1,029 simulated neighbouring-device trials and 50-device computational profiling',contribution:'Adds efficient processing, coverage analysis and spacing-constrained registration with pose-graph optimisation.'},
    {id:'safety',chapter:'6',label:'Perception and safety reasoning',title:'From 3D Perception to Safety Reasoning: An Intelligent Hybrid Framework for Real-Time Underground Mine Monitoring',authors:'P. Ranasinghe, S. Raval, D. Patra, B. Banerjee and I. Canbulat',venue:'Expert Systems with Applications (2026), 134601 · DOI 10.1016/j.eswa.2026.134601',status:'Published journal article',url:'https://doi.org/10.1016/j.eswa.2026.134601',evidence:'Real roadway scans, controlled object placement, simulation and 115 controlled hazard scenarios',contribution:'Combines neural perception, uncertainty signals, temporal graphs, safety rules, local LLM reasoning and historical memory.',versionNote:'UNSW Research and the public repository identify the journal article. arXiv 2606.03460 is an earlier “A Graph-Based Framework” version.'},
    {id:'dome',chapter:'Appendix A',label:'Dome-refraction foundation',title:'LiDAR Through Domes: Modelling, Simulation, and Correction of Refraction',authors:'P. Ranasinghe, D. Patra, B. Banerjee and S. Raval',venue:'IEEE IST 2025 · DOI 10.1109/IST66504.2025.11268399',status:'Published conference paper',url:'https://ieeexplore.ieee.org/document/11268399',evidence:'Analytical ray tracing, physics simulation and controlled indoor measurements',contribution:'Earlier dome-refraction treatment; shared results with Section 3.2 are not independent contributions.'}
  ],
  repositories: [
    {name:'single-shot-lidar-camera-calibration',title:'Align the two sensors',group:'calibration',type:'Command-line tool',visibility:'Public',problem:'A camera pixel and a LiDAR point use different coordinate systems.',approach:'Detect a checkerboard in an image and in a spherical LiDAR intensity view, fit a virtual lattice, then refine the transform.',inputs:'One image and corresponding intensity-bearing point cloud; ROS1/ROS2 bags or offline files.',outputs:'Sensor transformation matrices and reprojection quality checks.',role:'Spatial alignment before fusion.',papers:['spatial'],status:'Research implementation',related:['Sensor_Computer','enclosure-aware-lidar-correction']},
    {name:'enclosure-aware-lidar-correction',title:'Account for the protective dome',group:'calibration',type:'Browser app',visibility:'Public',problem:'Transparent protective domes bend outgoing and returning light.',approach:'Analytical two-interface ray tracing and an interpolated lookup table correct refraction. Enclosure Lab explores the geometry.',inputs:'Dome geometry, optical properties, sensor position and point clouds.',outputs:'Corrected clouds, lookup tables, configurations and plots.',role:'Optical correction and design exploration.',papers:['measurement','dome'],status:'Research toolkit and interactive demonstrator',related:['Sensor_Computer']},
    {name:'livox-avia-camera-timing',title:'Find the observation-time offset',group:'calibration',type:'Browser app',visibility:'Public',problem:'Equal timestamps can represent different moments of observation.',approach:'Estimate rotating-target angles from camera and LiDAR ROS1 recordings, then compare angle histories.',inputs:'Recorded camera and Livox Avia topics, calibration and target settings.',outputs:'Angle tracks, estimated time offsets, quality checks and reports.',role:'Observation-based temporal analysis.',papers:['measurement','timing'],status:'Recording-analysis studio',related:['rotating-target-calibration-studio']},
    {name:'rotating-target-calibration-studio',title:'Explore sensor timing',group:'calibration',type:'Browser app',visibility:'Public',problem:'A temporal method should work across different sensor acquisition patterns.',approach:'Interactively design a rotating target, place sensors, compare estimators and run parameter sweeps.',inputs:'Target geometry, built-in or custom sensor models, rotation and timing conventions.',outputs:'Angle and timing estimates, error statistics and scenario comparisons.',role:'Interactive explanation and simulation of target generalisation.',papers:['timing'],status:'Standalone simulation demonstrator',related:['livox-avia-camera-timing']},
    {name:'Sensor_Computer',title:'Turn sensor streams into a 3D view',group:'sensing',type:'Command-line tool',visibility:'Public',problem:'Independent camera, LiDAR and IMU streams must become useful live observations.',approach:'ROS Noetic acquisition, alignment, filtering, low-light processing and point-cloud colourisation on the sensing computer.',inputs:'FLIR Blackfly S images, Livox Avia LiDAR/IMU data and calibration settings.',outputs:'Colourised clouds and auxiliary streams through TCPROS or ROSBridge.',role:'Device-side acquisition and processing.',papers:['hardware','array','colour'],status:'Device software stack; deployment evidence is platform-specific',related:['Central_Monitoring_Platform','3D_monitoring_device_simulation_underground']},
    {name:'3D_monitoring_device_simulation_underground',title:'Explore a virtual longwall',group:'sensing',type:'Simulation',visibility:'Private',problem:'Coverage, acquisition and processing need repeatable test environments.',approach:'ROS/Gazebo simulation of dome-mounted devices, including single and three-device modes and isolated ROS masters.',inputs:'Virtual geometry, sensor models, device settings and scene conditions.',outputs:'Simulated sensor streams, ground truth and fault-isolation tests.',role:'Supporting simulation across integration and reconstruction.',papers:['hardware','array'],status:'Simulation; details from supplied portfolio overview',related:['Sensor_Computer','Multi_device_reconstruction-pose_graph']},
    {name:'Lidar_camera_FOV_analysis',title:'Plan what each device can see',group:'reconstruction',type:'Analysis tool',visibility:'Private',problem:'Canopy geometry and mounting angle can leave gaps between views.',approach:'Analyse LiDAR/camera field-of-view overlap, roof clipping, rotations and multi-device layouts.',inputs:'Sensor geometry, orientation, stand-off distance and colourised clouds.',outputs:'Coverage plots, overlap estimates and viewing-geometry visualisations.',role:'Coverage analysis supporting an array design.',papers:['array'],status:'Supporting analysis; details from supplied overview',related:['Multi_device_reconstruction-pose_graph','Central_Monitoring_Platform']},
    {name:'Multi_device_reconstruction-pose_graph',title:'Put neighbouring views together',group:'reconstruction',type:'Desktop app',visibility:'Private',problem:'Repeated supports can produce a good surface fit at the wrong physical position.',approach:'Combine IMU/roof alignment, overlap registration and pose-graph optimisation; inspect results in a calibration workbench.',inputs:'Adjacent point clouds, orientation estimates, spacing priors and optional simulated ground truth.',outputs:'Device transforms, aligned clouds and evaluation plots.',role:'Common-frame reconstruction research.',papers:['array'],status:'Research workbench; simulated array evidence',related:['Central_Monitoring_Platform','Lidar_camera_FOV_analysis']},
    {name:'Dynamic_Object_Detection',title:'Dynamic object detection and removal',group:'reconstruction',type:'Browser app',visibility:'Private',problem:'Detect moving objects and separate them from the background for reconstruction.',approach:'Build a stable point-cloud background, compensate small sensor motion and identify changing foreground regions.',inputs:'Point-cloud folders or live clouds with per-device settings.',outputs:'Moving-point sets, bounding boxes and detection diagnostics.',role:'Supporting movement detection and reconstructed-scene inspection.',papers:['array'],status:'Supporting tool; details from supplied overview',related:['Central_Monitoring_Platform']},
    {name:'Meshing_toolkit',title:'Meshing toolkit',group:'reconstruction',type:'Command-line tool',visibility:'Public',problem:'A point cloud is useful, but some tasks need a continuous surface.',approach:'Reconstruct coloured open meshes with improved Ball Pivoting and Poisson methods; compare held-out consistency.',inputs:'PCD/PLY point clouds.',outputs:'Coloured surface meshes, benchmark figures and comparison reports.',role:'Further geometric representation and analysis.',papers:['synthesis'],status:'Research meshing and benchmarking toolkit',related:['Multi_device_reconstruction-pose_graph']},
    {name:'Central_Monitoring_Platform',title:'Inspect the whole system',group:'reconstruction',type:'Desktop app',visibility:'Private',problem:'Operators need one place to inspect multiple streams and reconstructed scenes.',approach:'An Electron Windows interface receives clouds, IMU and temperature; supports recording, filtering, measurements and reconstruction.',inputs:'ROSBridge/TCPROS streams, device configuration and transformation settings.',outputs:'Live individual/combined views, recordings, measurements and diagnostics.',role:'Surface monitoring and control interface.',papers:['array','hardware'],status:'Documented desktop application; user guide v3 describes application 1.0.1',related:['Sensor_Computer','Multi_device_reconstruction-pose_graph','Dynamic_Object_Detection']},
    {name:'Scene-Graph_Mine-Safety',title:'Give the scene safety context',group:'interpretation',type:'Browser app',visibility:'Public',problem:'Geometry alone does not explain who is near what, or how a situation develops.',approach:'MinkUNet perception, uncertainty, scene/temporal graphs, deterministic rules, local LLM reasoning and GraphRAG memory.',inputs:'Colourised point clouds, models, rule settings and historical context.',outputs:'Semantic detections, graphs, hazard evidence and reasoning records.',role:'Safety interpretation; MineGraph Studio demonstrates single-frame inspection.',papers:['safety'],status:'Research framework and single-frame demonstrator',related:['Central_Monitoring_Platform']},
    {name:'Creep_Monitoring',title:'Track gradual support movement',group:'extensions',type:'Desktop app',visibility:'Private',problem:'Slow relative movement can be difficult to recognise by eye.',approach:'A concept/prototype compares recorded scans with fixed 3DUID markers, marker fitting and optional IMU orientation.',inputs:'Timestamped LiDAR recordings, detected reference markers and optional IMU.',outputs:'Relative trajectories, displacement plots and scan comparisons.',role:'Further application for gradual relative roof-support movement.',papers:['synthesis'],status:'Concept/prototype; operational creep-monitoring validation not established',related:['Central_Monitoring_Platform']}
  ],
  connections: [
    {from:'Sensor_Computer',to:'Central_Monitoring_Platform',kind:'interface',label:'Colourised clouds · ROSBridge / TCPROS',basis:'Sensor software output and Central Monitoring user guide v3 transport definitions.'},
    {from:'single-shot-lidar-camera-calibration',to:'Sensor_Computer',kind:'method',label:'Extrinsic calibration parameters',basis:'Method relationship; automatic import between repositories is not established.'},
    {from:'enclosure-aware-lidar-correction',to:'Sensor_Computer',kind:'method',label:'Refraction correction / lookup tables',basis:'Shared enclosure-correction method; repository wiring is not established.'},
    {from:'livox-avia-camera-timing',to:'Sensor_Computer',kind:'method',label:'Estimated observation-time offsets',basis:'Timing analysis can inform acquisition alignment; no automatic configuration transfer is claimed.'},
    {from:'rotating-target-calibration-studio',to:'livox-avia-camera-timing',kind:'method',label:'Sensor architecture / target comparisons',basis:'Related temporal research, independently operated tools.'},
    {from:'3D_monitoring_device_simulation_underground',to:'Sensor_Computer',kind:'method',label:'Production-like pipeline testing',basis:'Simulation support recorded in the supplied portfolio.'},
    {from:'Lidar_camera_FOV_analysis',to:'Multi_device_reconstruction-pose_graph',kind:'method',label:'Viewing geometry and coverage',basis:'Supporting array geometry; no automatic parameter transfer claimed.'},
    {from:'Multi_device_reconstruction-pose_graph',to:'Central_Monitoring_Platform',kind:'method',label:'Device transforms and aligned scenes',basis:'Common reconstruction methods and transform concept; independent code-level integration remains unverified.'},
    {from:'Dynamic_Object_Detection',to:'Central_Monitoring_Platform',kind:'method',label:'Moving-object filtering',basis:'Both portfolio and monitoring guide describe dynamic-object features; cross-repository dependency unverified.'},
    {from:'Central_Monitoring_Platform',to:'Scene-Graph_Mine-Safety',kind:'future',label:'Reconstructed scenes → safety reasoning',basis:'Conceptual future end-to-end connection; direct Chapter 5-to-6 output consumption is not established.'},
    {from:'Central_Monitoring_Platform',to:'Creep_Monitoring',kind:'future',label:'Recorded clouds → relative movement',basis:'Proposed monitoring-to-prototype workflow; integrated deployment not established.'},
    {from:'Multi_device_reconstruction-pose_graph',to:'Meshing_toolkit',kind:'future',label:'Aligned point clouds → surface meshes',basis:'Compatible data concept; implemented repository interface not established.'}
  ]
};
