window.PAPER_FIGURES = [
  {
    "id": "registration-validation",
    "path": "public/assets/evidence/registration-validation.png",
    "source_file": "Journal Publications\\sensors-25-06582-v2_Published.pdf",
    "source_location": "Figure 8, PDF page 16",
    "caption": "Alignment of LiDAR and SfM point clouds with checkerboard projection validation.",
    "original_caption": "Figure 8. (a) Results of the point cloud registration process: Alignment of the LiDAR points with\nthe SfM‑generated point cloud. The correspondence score for each object is indicated below the\nrespective object, representing the percentage of LiDAR points that found matches in the SfM recon‑\nstruction. (b) Validation of the transformation matrix by projecting LiDAR points onto a checker‑\nboard plane.",
    "attribution": "Ranasinghe, Patra, Banerjee and Raval (2025), Sensors 25, 6582, Figure 8. CC BY 4.0. Figure area extracted from published PDF; panels and caption retained.",
    "source_url": "https://doi.org/10.3390/s25216582",
    "license": "https://creativecommons.org/licenses/by/4.0/",
    "reuse_status": "verified-open-license",
    "display_permission": "public-and-private",
    "change_note": "Page cropped to complete figure area; no panel or research result edited.",
    "featured_in_story": true,
    "paper_id": "spatial",
    "figure": 8,
    "story_title": "Check the alignment against shared geometry",
    "evidence_type": "Published calibration result",
    "story_description": "LiDAR points are registered against a structure-from-motion reconstruction, then projected onto a checkerboard for validation. These are the complete published calibration panels.",
    "width": 1361,
    "height": 617
  },
  {
    "id": "longwall-mounting",
    "path": "public/assets/evidence/longwall-mounting.png",
    "paper_id": "hardware",
    "figure": 1,
    "story_title": "Proposed sensing beneath the canopy",
    "evidence_type": "Manuscript schematic",
    "story_description": "The paper places the monitoring unit on a hydraulic roof support, with its scanning area facing the working zone. This is a proposed arrangement, not an installation photograph.",
    "width": 1376,
    "height": 676,
    "source_file": "Journal Publications\\Hardware device.docx",
    "source_location": "Figure 1; embedded word/media/image1.png",
    "source_title": "Design and Pre-Deployment Validation of a Flameproof LiDAR–Camera Unit for Colourised 3D Monitoring of Underground Longwall Operations",
    "source_version": "Author-supplied local manuscript inspected 8 October 2026; figure numbering belongs to this version, not necessarily the linked public edition.",
    "caption": "The paper places the monitoring unit on a hydraulic roof support, with its scanning area facing the working zone. This is a proposed arrangement, not an installation photograph.",
    "original_caption": "Fig. 1 Schematic of the proposed system mounted on the longwall roof support, showing the LiDAR scanning region (green cone) oriented toward the mining face.",
    "attribution": "P. Ranasinghe, B. Banerjee and S. Raval. Design and Pre-Deployment Validation of a Flameproof LiDAR–Camera Unit for Colourised 3D Monitoring of Underground Longwall Operations. Local manuscript, Figure 1.",
    "license": null,
    "source_url": null,
    "reuse_status": "author-authorized-for-this-hub",
    "display_permission": "public-and-private",
    "authorization_note": "The PhD author explicitly requested use of suitable paper figures in this app on 8 October 2026. This scoped authorization is not an open-content licence.",
    "change_note": "Complete embedded image copied byte-for-byte. No panels, annotations, colours or scientific results edited. White page background supplied by CSS.",
    "content_note": "Authored schematic; no partner hardware photograph.",
    "sha256": "8781873897f62b37368b4c602d2184e3dea5ae408fd00d3c75a9fe3adbfcc3ce",
    "featured_in_story": true
  },
  {
    "id": "unit-hardware-architecture",
    "path": "public/assets/evidence/unit-hardware-architecture.png",
    "paper_id": "hardware",
    "figure": 2,
    "story_title": "How the sensing unit connects",
    "evidence_type": "Manuscript architecture",
    "story_description": "The hardware diagram connects the camera, LiDAR, network switch and processing unit through the power and data interfaces. It explains the proposed architecture; it is not a site acceptance record.",
    "width": 1147,
    "height": 1286,
    "source_file": "Journal Publications\\Hardware device.docx",
    "source_location": "Figure 2; embedded word/media/image2.png",
    "source_title": "Design and Pre-Deployment Validation of a Flameproof LiDAR–Camera Unit for Colourised 3D Monitoring of Underground Longwall Operations",
    "source_version": "Author-supplied local manuscript inspected 8 October 2026; figure numbering belongs to this version, not necessarily the linked public edition.",
    "caption": "The hardware diagram connects the camera, LiDAR, network switch and processing unit through the power and data interfaces. It explains the proposed architecture; it is not a site acceptance record.",
    "original_caption": "Fig. 2 Hardware architecture of the proposed monitoring system, mounted inside the enclosure. The LiDAR and camera feeds are routed to the integrated processing unit via an internal Ethernet switch. The system consists of a LiDAR, camera, processing unit, and network switch, all interfaced through an IS-compliant power-and-data barrier to ensure safe operation in underground mining conditions.",
    "attribution": "P. Ranasinghe, B. Banerjee and S. Raval. Design and Pre-Deployment Validation of a Flameproof LiDAR–Camera Unit for Colourised 3D Monitoring of Underground Longwall Operations. Local manuscript, Figure 2.",
    "license": null,
    "source_url": null,
    "reuse_status": "author-authorized-for-this-hub",
    "display_permission": "public-and-private",
    "authorization_note": "The PhD author explicitly requested use of suitable paper figures in this app on 8 October 2026. This scoped authorization is not an open-content licence.",
    "change_note": "Complete embedded image copied byte-for-byte. No panels, annotations, colours or scientific results edited. White page background supplied by CSS.",
    "content_note": "Authored schematic; no partner hardware photograph.",
    "sha256": "3ae1c240829287228a4b3ecf01c403deb59a770a5953b4748ec7d13e38e45fae",
    "featured_in_story": true
  },
  {
    "id": "array-pose-graph",
    "path": "public/assets/evidence/array-pose-graph.png",
    "paper_id": "array",
    "figure": 15,
    "story_title": "Registration meets physical constraints",
    "evidence_type": "Manuscript method diagram",
    "story_description": "Neighbouring device poses are linked by registration edges and installation priors. Device 1 fixes the reference frame before the array is optimised.",
    "width": 1061,
    "height": 438,
    "source_file": "Journal Publications\\Array field deployment.docx",
    "source_location": "Figure 15; embedded word/media/image18.png",
    "source_title": "A Scalable Array of Integrated LiDAR–Camera Units for Continuous Colourised 3D Monitoring of Underground Longwall Operations",
    "source_version": "Author-supplied local manuscript inspected 8 October 2026; figure numbering belongs to this version, not necessarily the linked public edition.",
    "caption": "Neighbouring device poses are linked by registration edges and installation priors. Device 1 fixes the reference frame before the array is optimised.",
    "original_caption": "Figure 15: Pose-graph structure used for final merging. Registration and prior edges connect neighbouring device poses, allowing the full array to be optimised before point-cloud merging.",
    "attribution": "P. Ranasinghe, D. Patra, B. Banerjee, C. Ye, B. Nan and S. Raval. A Scalable Array of Integrated LiDAR–Camera Units for Continuous Colourised 3D Monitoring of Underground Longwall Operations. Local manuscript, Figure 15.",
    "license": null,
    "source_url": null,
    "reuse_status": "author-authorized-for-this-hub",
    "display_permission": "public-and-private",
    "authorization_note": "The PhD author explicitly requested use of suitable paper figures in this app on 8 October 2026. This scoped authorization is not an open-content licence.",
    "change_note": "Complete embedded image copied byte-for-byte. No panels, annotations, colours or scientific results edited. White page background supplied by CSS.",
    "content_note": "Authored method diagram, simulation output or interface displaying a synthetic longwall scene; no operating mine data.",
    "sha256": "bd85bb3e830520611e9400787fce0bc88730de598d41384e074d8c805da51323",
    "featured_in_story": true
  },
  {
    "id": "array-single-unit-cloud",
    "path": "public/assets/evidence/array-single-unit-cloud.png",
    "paper_id": "array",
    "figure": 17,
    "story_title": "What one simulated unit sees",
    "evidence_type": "Simulation output",
    "story_description": "A colourised point cloud from a single simulated unit shows the roof canopy, face, shearer, conveyor, floor and personnel object. This is distinct from the multi-device fusion result.",
    "width": 1377,
    "height": 784,
    "source_file": "Journal Publications\\Array field deployment.docx",
    "source_location": "Figure 17; embedded word/media/image20.png",
    "source_title": "A Scalable Array of Integrated LiDAR–Camera Units for Continuous Colourised 3D Monitoring of Underground Longwall Operations",
    "source_version": "Author-supplied local manuscript inspected 8 October 2026; figure numbering belongs to this version, not necessarily the linked public edition.",
    "caption": "A colourised point cloud from a single simulated unit shows the roof canopy, face, shearer, conveyor, floor and personnel object. This is distinct from the multi-device fusion result.",
    "original_caption": "Figure 17 shows the resulting colourised point cloud. The principal components of the longwall face are individually identifiable: the roof-support canopy above the device, the exposed mining face, the shearer, the conveyor, the floor, and a personnel object standing between the conveyor and the face. The output therefore provides the spatial context intended for remote assessment, allowing an operator to relate equipment positions and personnel locations to the surrounding structure rather than interpreting them from separate camera views.",
    "attribution": "P. Ranasinghe, D. Patra, B. Banerjee, C. Ye, B. Nan and S. Raval. A Scalable Array of Integrated LiDAR–Camera Units for Continuous Colourised 3D Monitoring of Underground Longwall Operations. Local manuscript, Figure 17.",
    "license": null,
    "source_url": null,
    "reuse_status": "author-authorized-for-this-hub",
    "display_permission": "public-and-private",
    "authorization_note": "The PhD author explicitly requested use of suitable paper figures in this app on 8 October 2026. This scoped authorization is not an open-content licence.",
    "change_note": "Complete embedded image copied byte-for-byte. No panels, annotations, colours or scientific results edited. White page background supplied by CSS.",
    "content_note": "Authored method diagram, simulation output or interface displaying a synthetic longwall scene; no operating mine data.",
    "sha256": "31e6dcfb848f389f70046389c122e956b4f316dda2b319fb76dd968cbac23f6b",
    "featured_in_story": true
  },
  {
    "id": "array-fusion-before-after",
    "path": "public/assets/evidence/array-fusion-before-after.png",
    "paper_id": "array",
    "figure": 18,
    "story_title": "Local frames become one wider scene",
    "evidence_type": "Simulation comparison",
    "story_description": "The same three device clouds are shown before and after fusion. Blue, green and red distinguish the devices. The lower panel places them in the common frame of Device 1.",
    "width": 1171,
    "height": 1039,
    "source_file": "Journal Publications\\Array field deployment.docx",
    "source_location": "Figure 18; embedded word/media/image21.png",
    "source_title": "A Scalable Array of Integrated LiDAR–Camera Units for Continuous Colourised 3D Monitoring of Underground Longwall Operations",
    "source_version": "Author-supplied local manuscript inspected 8 October 2026; figure numbering belongs to this version, not necessarily the linked public edition.",
    "caption": "The same three device clouds are shown before and after fusion. Blue, green and red distinguish the devices. The lower panel places them in the common frame of Device 1.",
    "original_caption": "Figure 18: Multi-device point clouds before and after chain-based fusion. (a) Local device frames before fusion. (b) Global frame after applying the proposed algorithm.",
    "attribution": "P. Ranasinghe, D. Patra, B. Banerjee, C. Ye, B. Nan and S. Raval. A Scalable Array of Integrated LiDAR–Camera Units for Continuous Colourised 3D Monitoring of Underground Longwall Operations. Local manuscript, Figure 18.",
    "license": null,
    "source_url": null,
    "reuse_status": "author-authorized-for-this-hub",
    "display_permission": "public-and-private",
    "authorization_note": "The PhD author explicitly requested use of suitable paper figures in this app on 8 October 2026. This scoped authorization is not an open-content licence.",
    "change_note": "Complete embedded image copied byte-for-byte. No panels, annotations, colours or scientific results edited. White page background supplied by CSS.",
    "content_note": "Authored method diagram, simulation output or interface displaying a synthetic longwall scene; no operating mine data.",
    "sha256": "303037e3f261af801f4405e508b3ccc41635e454bf39cce344db2899166c811c",
    "featured_in_story": true
  },
  {
    "id": "array-monitoring-interface",
    "path": "public/assets/evidence/array-monitoring-interface.png",
    "paper_id": "array",
    "figure": 8,
    "story_title": "The operator’s view",
    "evidence_type": "Manuscript application screenshot",
    "story_description": "The annotated Central Monitoring Platform shows a simulated scene alongside device status, orientation, display controls and measurement tools. It documents the desktop interface; it is not a live app embedded in this website.",
    "width": 1376,
    "height": 837,
    "source_file": "Journal Publications\\Array field deployment.docx",
    "source_location": "Figure 8; embedded word/media/image10.png",
    "source_title": "A Scalable Array of Integrated LiDAR–Camera Units for Continuous Colourised 3D Monitoring of Underground Longwall Operations",
    "source_version": "Author-supplied local manuscript inspected 8 October 2026; figure numbering belongs to this version, not necessarily the linked public edition.",
    "caption": "The annotated Central Monitoring Platform shows a simulated scene alongside device status, orientation, display controls and measurement tools. It documents the desktop interface; it is not a live app embedded in this website.",
    "original_caption": "Figure 8: Central monitoring application interface for surface-side visualisation and control",
    "attribution": "P. Ranasinghe, D. Patra, B. Banerjee, C. Ye, B. Nan and S. Raval. A Scalable Array of Integrated LiDAR–Camera Units for Continuous Colourised 3D Monitoring of Underground Longwall Operations. Local manuscript, Figure 8.",
    "license": null,
    "source_url": null,
    "reuse_status": "author-authorized-for-this-hub",
    "display_permission": "public-and-private",
    "authorization_note": "The PhD author explicitly requested use of suitable paper figures in this app on 8 October 2026. This scoped authorization is not an open-content licence.",
    "change_note": "Complete embedded image copied byte-for-byte. No panels, annotations, colours or scientific results edited. White page background supplied by CSS.",
    "content_note": "Authored method diagram, simulation output or interface displaying a synthetic longwall scene; no operating mine data.",
    "sha256": "5d6dde121040071151d2f553739faae1681f23538e40917d77c52350641283be",
    "featured_in_story": true
  },
  {
    "id": "safety-scene-graph-pipeline",
    "path": "public/assets/evidence/safety-scene-graph-pipeline.png",
    "paper_id": "safety",
    "figure": 7,
    "story_title": "From relationships to contextual evidence",
    "evidence_type": "Manuscript method diagram",
    "story_description": "The full pipeline links object relationships to temporal tracking, rule evaluation, contextual reasoning and a memory archive. The research diagram includes an 8 m graph edge threshold and a 10 s rolling window; these are study settings, not universal safety limits.",
    "width": 1417,
    "height": 1165,
    "source_file": "Journal Publications\\Decision support.docx",
    "source_location": "Figure 7; embedded word/media/image7.png",
    "source_title": "From 3D Perception to Safety Reasoning: An Intelligent Hybrid Framework for Real-Time Underground Mine Monitoring",
    "source_version": "Author-supplied local manuscript inspected 8 October 2026; figure numbering belongs to this version, not necessarily the linked public edition.",
    "caption": "The full pipeline links object relationships to temporal tracking, rule evaluation, contextual reasoning and a memory archive. The research diagram includes an 8 m graph edge threshold and a 10 s rolling window; these are study settings, not universal safety limits.",
    "original_caption": "Figure 7: Scene graph construction, temporal graph tracking, and memory unit generation pipeline.Nodes represent detected objects with attributes , and edges encode spatial relations within an 8 m threshold. Consecutive scene graphs are linked via inter-frame association over a 10 s rolling window to extract kinematic descriptors. Each reasoning step produces a memory unit , which is stored for longitudinal retrieval.",
    "attribution": "P. Ranasinghe, S. Raval, D. Patra, B. Banerjee and I. Canbulat. From 3D Perception to Safety Reasoning: An Intelligent Hybrid Framework for Real-Time Underground Mine Monitoring. Local manuscript, Figure 7.",
    "license": null,
    "source_url": null,
    "reuse_status": "author-authorized-for-this-hub",
    "display_permission": "public-and-private",
    "authorization_note": "The PhD author explicitly requested use of suitable paper figures in this app on 8 October 2026. This scoped authorization is not an open-content licence.",
    "change_note": "Complete embedded image copied byte-for-byte. No panels, annotations, colours or scientific results edited. White page background supplied by CSS.",
    "content_note": "Authored method diagram; no mine scan or partner photograph.",
    "sha256": "24238c880ec00a3ca6414f57f837fa11826333d22f3ef3dab3b4ddbb1336e470",
    "featured_in_story": true
  }
];
